### ISSUE TITLE
Release prebuilt robotjs packages

### ISSUE THREAD

**Issue by saghul** [jitsi/jitsi-meet-electron-sdk#138]
Do so in https://github.com/jitsi/robotjs which we were using before. We might need to publish the package on npm I think, we can do that as `@jitsi/robotjs`. The package has been "orphaned" for years, AFAICT, and we have no intention of becoming the maintainers, but providing prebuilt packages, which can be done with a GH action easily would simplify things.

**Comment by csett86** [comment]
To get this started I have provided all upstream an my (context-aware) commits via https://github.com/jitsi/robotjs/pull/2

**Comment by csett86** [comment]
Followup: Draft PR to provide prebuilds via GH actions: https://github.com/jitsi/robotjs/pull/3

**Comment by csett86** [comment]
PR for prebuild robotjs packages is now ready: https://github.com/jitsi/robotjs/pull/5

**Comment by csett86** [comment]
Prebuilds of robotjs are now ready to be tested: https://github.com/jitsi/robotjs/releases/tag/v0.6.5

**Comment by saghul** [comment]
🚀

**Comment by saghul** [comment]
Published on npm.
