### ISSUE TITLE
Release 3.0.0

### ISSUE THREAD

**Issue by saghul** [jitsi/jitsi-meet-electron-sdk#148]
I no longer have any blockers. The migration to a module needs a bit more work, we can do that later. I opened a draft PR.

**Comment by csett86** [comment]
Alright, then I would prep the 3.0.0 proper release based on latest master.

**Comment by csett86** [comment]
Done, including npm (https://www.npmjs.com/package/@jitsi/electron-sdk/v/3.0.0) and prebuilds https://github.com/jitsi/jitsi-meet-electron-sdk/releases/tag/v3.0.0

**Comment by saghul** [comment]
🚀🚀🚀
