### ISSUE TITLE
Screen Share dialog showing loading .... 

### ISSUE THREAD

**Issue by kamillec** [jitsi/jitsi-meet-electron-sdk#185]
I am using Jitsi electron  project using angular. My application has a problem with the screen share both on mac and windows. 
<img width="631" alt="Screenshot 2022-01-27 at 2 23 12 AM" src="https://user-images.githubusercontent.com/94394237/151249412-992de853-eabc-4eda-a334-5832eb8b8afa.png">

The logs are showing following error
<img width="556" alt="Screenshot 2022-01-27 at 2 23 50 AM" src="https://user-images.githubusercontent.com/94394237/151249465-36fbb12b-d181-4892-bb1b-af41f5935c2b.png">
<img width="544" alt="Screenshot 2022-01-27 at 2 23 38 AM" src="https://user-images.githubusercontent.com/94394237/151249475-2b13097f-f2f0-4d3e-a9ba-3cda42609c1f.png">

When I used jistsi meet electron SDK the app is stuck when I used setupScreenSharingRender(this.api) 

I am using the latest SDK and apis. 

Please help me resolving this issue. 

Regards

**Comment by csett86** [comment]
Unfortunately we do not habe capacity to use this issue tracker as a support forum. 

Thank you for your understanding, @kamillec
