### ISSUE TITLE
Missing prebuilts

### ISSUE THREAD

**Issue by saghul** [jitsi/jitsi-meet-electron-sdk#204]
Looks like the last few releases have missing prebuilt artifacts.

**Comment by csett86** [comment]
Cannot reproduce, for latest (3.0.6) the prebuilds are included in the npm package (as expected since #159):

```
ls  node_modules/@jitsi/electron-sdk/prebuilds/*
node_modules/@jitsi/electron-sdk/prebuilds/darwin-x64+arm64:
node.napi.node

node_modules/@jitsi/electron-sdk/prebuilds/linux-x64:
node.napi.node

node_modules/@jitsi/electron-sdk/prebuilds/win32-ia32:
node.napi.node

node_modules/@jitsi/electron-sdk/prebuilds/win32-x64:
node.napi.node
```

It is expected that they are no longer attached to the github release, but they are now bundled in the package hosted on npm.

**Comment by saghul** [comment]
Oh wait I thought we released them on GH. Hum, I'll dig deeper.

**Comment by csett86** [comment]
We had them separately on GH when we were using [prebuild](https://github.com/prebuild/prebuild), but when switching to [prebuildify](https://github.com/prebuild/prebuildify), they are now included in the package from npm itself.

electron-builder may print that its rebuilding native dependencies, but in reality its not, just using the prebuild binaries inside the package, nontheless.

This is eg visible as the jitsi-meet-electron no longer contains any development headers for robotjs, but still works fine: https://github.com/jitsi/jitsi-meet-electron/commit/4237c5d1a55fde46fb985e5cf7c431e31acdb886

**Comment by csett86** [comment]
Whats currently missing is any linux arm variant (arm64 or armv7), but we did not have that previously as well...

**Comment by saghul** [comment]
Ah thanks for the insight. Some colleagues thought it's being rebuilt, looks like it isn't :-)

**Comment by csett86** [comment]
Then I would consider this closed here
