### ISSUE TITLE
Autopublish?

### ISSUE THREAD

**Issue by saghul** [jitsi/jitsi-meet-electron-sdk#258]
Some time ago I created this, which we use on some of our JS packages: https://github.com/jitsi/gh-action-autopublish

The idea is simple: bbump the minor and create a new npm release when a PR gets merged.

If a PR needs to change the minor / major, that can be done as part of the PR and the script notices it and skips the bump.

Thoughts on adding it here?

**Comment by quitrk** [comment]
Shouldn't we worry about releasing versions for users who get to install latest, when latest is broken?

**Comment by hristoterezov** [comment]
+1 for auto publish from me!

I guess if we find out that the latest is broken we can push a hot fix or something.

**Comment by csett86** [comment]
Agree as well, we just need to have the prebuildify matrix step and collection of results included so that the npm published package still contains the prebuild binaries

**Comment by csett86** [comment]
Its nearly there, but failing due to protected master branch:

> remote: error: GH006: Protected branch update failed for refs/heads/master.

Is that something you can fix in the settings of the repo @saghul?

**Comment by saghul** [comment]
Fixed now.
