### ISSUE TITLE
Electron update to v.19.X, can not get source of screen share

### ISSUE THREAD

**Issue by codeingforcoffee** [jitsi/jitsi-meet-electron-sdk#300]
desktopCapturer.getSources has been removed since v17.X, 
but desktopCapturer.getSources used in .render.js,

has any solutions for it?

https://www.electronjs.org/docs/latest/breaking-changes#%E5%B7%B2%E7%A7%BB%E9%99%A4%E6%B8%B2%E6%9F%93%E5%99%A8%E4%B8%AD%E7%9A%84-desktopcapturergetsources

**Comment by csett86** [comment]
Sure, its supported since version 3.0.5 because of https://github.com/jitsi/jitsi-meet-electron-sdk/pull/186
