### ISSUE TITLE
ScreenShare: window.JitsiMeetElectron is undefined due to loading external Jitsi Meets domain

### ISSUE THREAD

**Issue by wbigert** [jitsi/jitsi-meet-electron-sdk#368]
Hello,

In the screensharing/renderer.js an attempt is made to add JitsiMeetElectron property to contentWindow of the current iframe. 

https://github.com/jitsi/jitsi-meet-electron-sdk/blob/master/screensharing/render.js

However, since my Electron app is loading a React app server running on localhost. And the React app is instantiating a Jitsi Meets iframe with a different source url, it is unable to add the property. Or at least that's my leading theory of why the property is not being properly added to the external Jitsi Meets iframe window. If I log the content of this._iframe.contentWindow.JitsiMeetElectron directly after setting it in the renderer.js file, it shows up as undefined. And when the desktoppicker of the jitsi meets API attempts to access it when the user attempts to screen share, it just shows up as undefined.

I am puzzled on how this is supposed to work, as I assume my scenario should be a common one, given that electron apps run locally, and should load external jitsi meeting pages from other domains? I did disable web security already for all of my Electron Windows. And I added the special cors commands mentioned in the README. Is it more common that the jitsi meet and Electron app window are running on the same domain?

Could this issue be the same as #325 ?

**Comment by saghul** [comment]
We have changed the way we implement screen-sharing delegation. I see we are still injeting the old code there, but we really shouldn't, or rather we shouldn't fail when we do. I'll make a PR.

**Comment by wbigert** [comment]
> We have changed the way we implement screen-sharing delegation. I see we are still injeting the old code there, but we really shouldn't, or rather we shouldn't fail when we do. I'll make a PR.

I see, thank you for the response. If anyone else comes across this and just wants screen sharing to work with a similar setup as mine, check this out: https://github.com/jitsi/jitsi-meet-electron-sdk/issues/358#issuecomment-1893722994

**Comment by saghul** [comment]
FOr people like you, we are planning on releasing a `-lite` SDK.
